#!/usr/bin/env bash
#
# install all files to ~ by symlinking them,
# this way, updating them is as simple as git pull
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: May 25, 2012
# License: MIT

# makes "defaults" command print to screen
defaults() {
	echo defaults "$@"
	command defaults "$@"
}

# verbose ln, because `ln -v` is not portable
symlink() {
	printf '%55s -> %s\n' "${1/#$HOME/\~}" "${2/#$HOME/\~}"
	ln -nsf "$@"
}

git submodule init
git submodule update

# Link dotfiles
dotfiles=(
	bash_completion
	bash_profile
	bashrc
	htoprc
	screenrc
	tmux.conf
	vimrc
	vim
)
# i've become famous - whoops. because of this, people like to install my
# dotfiles without customizing them so then they get my git config and "become"
# me and it's super annoying.  so, hide my own git config behind `-f` and i'll
# just handle that myself.
if [[ $1 == '-f' ]]; then
	dotfiles+=(gitconfig)
fi

for f in "${dotfiles[@]}"; do
	[[ -d ~/.$f && ! -L ~/.$f ]] && rm -r ~/."$f"
	symlink "$PWD/$f" ~/."$f"
done

# neovim
symlink ~/.vim ~/.config/nvim

# Setup bics
if [[ ! -d ~/.bics ]]; then
	echo 'installing bics'
	bash <(curl -sSL https://raw.githubusercontent.com/bahamas10/bics/master/bics) init
	rm -r ~/.bics/plugins
	symlink "$PWD/bics-plugins" ~/.bics/plugins
fi

# Keyboard shortcuts for Mac OS X
if [[ -d ~/Library ]]; then
	echo 'installing mac keyboard shourtcuts'
	mkdir -p ~/Library/KeyBindings
	symlink "$PWD/DefaultKeyBinding.dict" ~/Library/KeyBindings/DefaultKeyBinding.dict
fi

if [[ -t 1 ]]; then
	vim '+PlugInstall --sync' +qa
else
	printf "may need to run:\n\tvim +'PlugInstall --sync' +qa\n"
fi

true
